# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalmixpmle_z2 <- function(bs, ys, zs, mu0s, sigma0s, m, p, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L) {
    .Call('normalregMix_normalmixpmle_z2', PACKAGE = 'normalregMix', bs, ys, zs, mu0s, sigma0s, m, p, an, maxit, ninits, tol, tau, h, k)
}

regmixpmle_z2 <- function(bs, ys, xs, zs, mu0s, sigma0s, m, p, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L) {
    .Call('normalregMix_regmixpmle_z2', PACKAGE = 'normalregMix', bs, ys, xs, zs, mu0s, sigma0s, m, p, an, maxit, ninits, tol, tau, h, k)
}

